name: CI
on: [push]
jobs:
  Explore:
   runs-on: ubuntu-latest
   steps:
    - name: checkout
      uses: actions/checkout@v1
    - run: cd backend && npm i
    - run: cd backend && npm run build
   